[project]
name = "careless-whisper"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "openai-whisper>=20250625",
    "torch>=2.8.0",
    "torchaudio>=2.8.0",
    "torchvision>=0.23.0",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.7",
]
